sonar.projectKey=LinconCarmo_pizzaria-api
sonar.organization=linconcarmo
sonar.projectName=pizzaria-api

sonar.sources=src
sonar.tests=test
sonar.exclusions=src/infra/prisma/migrations/**
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
